// products-data.js - Save this in your project root
const productsData = [
    {
        id: 'product-1',
        name: "Rose Petal",
        subtitle: "Simply Rosy",
        description: "Gentle cleanser with rose petals that nourishes skin and leaves it feeling soft and supple.",
        detailedDescription: "Immerse yourself in the delicate fragrance of handpicked rose petals. Our Rose Petal Soap is crafted with organic roses and nourishing oils to gently cleanse while maintaining your skin's natural moisture balance. Perfect for all skin types, especially dry and sensitive skin.",
        price: 299,
        mrp: 399,
        discount: "25% OFF",
        image: "images/rosepetal_soap_2.jpg",
        thumbnail1: "rose-soap.jpeg",
        thumbnail2: "soap.jpg",
        alt: "Aura-Cleanse Rose Petal Handmade Soap - Natural Ayurvedic Soap with Rose Petals for Soft Skin",
        size: "100g",
        weight: "100g",
        category: "floral",
        ingredients: [
            { name: "Organic Rose Petals", description: "Handpicked from organic farms, rich in antioxidants and natural fragrance" },
            { name: "Coconut & Olive Oil", description: "Deeply moisturizing and antibacterial, provides a rich lather" },
            { name: "Shea Butter", description: "Intensely hydrating with vitamins A and E" },
            { name: "Rose Fragrance Oil", description: "Pure steam-distilled oil for soft floral aroma" }
        ],
        rating: 4.7,
        reviews: 128
    },
    {
        id: 'product-2',
        name: "Red Sandal",
        subtitle: "Soothes Skin",
        description: "Calming soap with red sandalwood known for its skin-soothing properties and ability to reduce inflammation.",
        detailedDescription: "Red Sandalwood soap harnesses the ancient Ayurvedic wisdom to calm and soothe irritated skin. Known for its anti-inflammatory properties, this soap reduces redness and promotes even skin tone.",
        price: 329,
        mrp: 429,
        discount: "23% OFF",
        image: "soap.jpg",
        thumbnail1: "soap.jpg",
        thumbnail2: "soap.jpg",
        alt: "Aura-Cleanse Red Sandalwood Soap - Ayurvedic Soothing Soap for Skin Inflammation",
        size: "100g",
        weight: "100g",
        category: "ayurvedic",
        ingredients: [
            { name: "Red Sandalwood Powder", description: "Known for its cooling and anti-inflammatory properties" },
            { name: "Coconut Oil", description: "Moisturizes and creates rich lather" },
            { name: "Aloe Vera", description: "Soothes and heals irritated skin" },
            { name: "Essential Oils", description: "Natural fragrance for therapeutic benefits" }
        ],
        rating: 4.5,
        reviews: 96
    },
    {
        id: 'product-3',
        name: "Manjistha",
        subtitle: "Skin Brightener",
        description: "Ayurvedic formula that helps brighten skin tone, reduce pigmentation, and promote an even complexion.",
        detailedDescription: "Manjistha, known as the 'skin brightener' in Ayurveda, helps reduce pigmentation and dark spots while promoting an even skin tone and radiant glow.",
        price: 349,
        mrp: 449,
        discount: "22% OFF",
        image: "soap.jpg",
        thumbnail1: "soap.jpg",
        thumbnail2: "soap.jpg",
        alt: "Aura-Cleanse Manjistha Soap - Natural Skin Brightening Soap for Even Complexion",
        size: "100g",
        weight: "100g",
        category: "ayurvedic",
        ingredients: [
            { name: "Manjistha Root Powder", description: "Natural skin brightener and blood purifier" },
            { name: "Sandalwood", description: "Cooling and soothing for the skin" },
            { name: "Multani Mitti", description: "Deep cleanses and removes impurities" }
        ],
        rating: 4.6,
        reviews: 87
    },
    {
        id: 'product-4',
        name: "Urad Dal",
        subtitle: "Glowing Skin",
        description: "Enriched with Urad Dal to exfoliate gently, remove dead skin cells, and reveal naturally glowing skin.",
        detailedDescription: "Urad Dal soap provides gentle exfoliation to remove dead skin cells and reveal naturally glowing, radiant skin. Perfect for dull and tired-looking skin.",
        price: 279,
        mrp: 379,
        discount: "26% OFF",
        image: "soap.jpg",
        thumbnail1: "soap.jpg",
        thumbnail2: "soap.jpg",
        alt: "Aura-Cleanse Urad Dal Soap - Exfoliating Soap for Glowing Natural Skin",
        size: "100g",
        weight: "100g",
        category: "exfoliating",
        ingredients: [
            { name: "Urad Dal Flour", description: "Gentle exfoliant for removing dead skin cells" },
            { name: "Gram Flour", description: "Cleanses and brightens skin" },
            { name: "Turmeric", description: "Antibacterial and brightening properties" }
        ],
        rating: 4.4,
        reviews: 72
    },
    {
        id: 'product-5',
        name: "Straw Berry",
        subtitle: "Antioxidant Booster",
        description: "Packed with berry antioxidants to fight free radicals, protect skin from environmental damage.",
        detailedDescription: "Strawberry soap is rich in antioxidants and vitamin C, protecting your skin from environmental damage while leaving it soft and refreshed with a sweet berry fragrance.",
        price: 369,
        mrp: 469,
        discount: "21% OFF",
        image: "images/strawberry_soap_2.jpg",
        thumbnail1: "soap.jpg",
        thumbnail2: "soap.jpg",
        alt: "Aura-Cleanse Strawberry Soap - Antioxidant Rich Soap for Skin Protection",
        size: "100g",
        weight: "100g",
        category: "fruity",
        ingredients: [
            { name: "Strawberry Extract", description: "Rich in antioxidants and vitamin C" },
            { name: "Vitamin E", description: "Moisturizes and protects skin" },
            { name: "Berry Seeds", description: "Gentle natural exfoliant" }
        ],
        rating: 4.8,
        reviews: 145
    },
    {
        id: 'product-6',
        name: "Coffee",
        subtitle: "Skin Tightener",
        description: "Coffee grounds help tighten skin, reduce cellulite appearance, and provide antioxidant benefits.",
        detailedDescription: "Coffee soap with ground coffee beans provides gentle exfoliation while caffeine helps tighten skin and reduce the appearance of cellulite.",
        price: 319,
        mrp: 419,
        discount: "24% OFF",
        image: "soap.jpg",
        thumbnail1: "soap.jpg",
        thumbnail2: "soap.jpg",
        alt: "Aura-Cleanse Coffee Soap - Skin Tightening Soap with Coffee Grounds",
        size: "100g",
        weight: "100g",
        category: "exfoliating",
        ingredients: [
            { name: "Coffee Grounds", description: "Natural exfoliant rich in antioxidants" },
            { name: "Caffeine", description: "Tightens skin and reduces cellulite appearance" },
            { name: "Cocoa Butter", description: "Deeply moisturizing" }
        ],
        rating: 4.3,
        reviews: 68
    },
    {
        id: 'product-7',
        name: "Vetiver",
        subtitle: "Earthy Aroma",
        description: "Deep cleansing soap with vetiver's earthy aroma that calms the mind while purifying the skin.",
        detailedDescription: "Vetiver soap offers deep cleansing with its earthy, grounding aroma that calms the mind while thoroughly purifying the skin of impurities.",
        price: 299,
        mrp: 399,
        discount: "25% OFF",
        image: "soap.jpg",
        thumbnail1: "soap.jpg",
        thumbnail2: "soap.jpg",
        alt: "Aura-Cleanse Vetiver Soap - Earthy Aroma Soap for Mind Calming and Skin Purification",
        size: "100g",
        weight: "100g",
        category: "aromatherapy",
        ingredients: [
            { name: "Vetiver Root", description: "Earthy aroma with calming properties" },
            { name: "Neem", description: "Purifies and cleanses skin" },
            { name: "Clay", description: "Draws out impurities" }
        ],
        rating: 4.5,
        reviews: 59
    },
    {
        id: 'product-8',
        name: "Wild Turmeric",
        subtitle: "Anti-Bacterial",
        description: "Powerful antibacterial and antifungal properties help treat skin infections and promote clear skin.",
        detailedDescription: "Wild Turmeric soap harnesses the powerful antibacterial and antifungal properties of turmeric to treat skin infections, reduce acne, and promote clear, healthy skin.",
        price: 339,
        mrp: 439,
        discount: "23% OFF",
        image: "soap.jpg",
        thumbnail1: "soap.jpg",
        thumbnail2: "soap.jpg",
        alt: "Aura-Cleanse Wild Turmeric Soap - Antibacterial Soap for Clear Skin",
        size: "100g",
        weight: "100g",
        category: "medicinal",
        ingredients: [
            { name: "Wild Turmeric", description: "Powerful antibacterial and anti-inflammatory" },
            { name: "Neem", description: "Purifies and heals skin" },
            { name: "Honey", description: "Moisturizes and has antibacterial properties" }
        ],
        rating: 4.7,
        reviews: 112
    },
    {
        id: 'product-9',
        name: "Kuppaimeni",
        subtitle: "Skin Healer",
        description: "Traditional herb known for healing skin ailments, reducing irritation, and promoting skin regeneration.",
        detailedDescription: "Kuppaimeni, a traditional medicinal herb, is known for its skin healing properties. It reduces irritation, soothes skin conditions, and promotes healthy skin regeneration.",
        price: 289,
        mrp: 389,
        discount: "26% OFF",
        image: "soap.jpg",
        thumbnail1: "soap.jpg",
        thumbnail2: "soap.jpg",
        alt: "Aura-Cleanse Kuppaimeni Soap - Skin Healing Soap with Traditional Herbs",
        size: "100g",
        weight: "100g",
        category: "medicinal",
        ingredients: [
            { name: "Kuppaimeni Leaves", description: "Traditional herb for skin healing" },
            { name: "Aloe Vera", description: "Soothes and moisturizes" },
            { name: "Tulsi", description: "Purifying and antibacterial" }
        ],
        rating: 4.6,
        reviews: 84
    },
    {
        id: 'product-10',
        name: "Green Gram",
        subtitle: "Skin Energiser",
        description: "Green gram flour gently exfoliates and energizes skin, removing impurities and leaving it refreshed.",
        detailedDescription: "Green Gram soap gently exfoliates with green gram flour, removing impurities and dead skin cells to reveal energized, refreshed, and radiant skin.",
        price: 269,
        mrp: 369,
        discount: "27% OFF",
        image: "soap.jpg",
        thumbnail1: "soap.jpg",
        thumbnail2: "soap.jpg",
        alt: "Aura-Cleanse Green Gram Soap - Exfoliating Soap for Energized Skin",
        size: "100g",
        weight: "100g",
        category: "exfoliating",
        ingredients: [
            { name: "Green Gram Flour", description: "Gentle exfoliant and skin brightener" },
            { name: "Oatmeal", description: "Soothes and moisturizes skin" },
            { name: "Milk", description: "Softens and nourishes skin" }
        ],
        rating: 4.4,
        reviews: 76
    },
    {
        id: 'product-11',
        name: "Aloe Vera",
        subtitle: "Nourish & Renew",
        description: "Soothing aloe vera deeply hydrates, heals, and renews skin, perfect for sensitive or sun-exposed skin.",
        detailedDescription: "Aloe Vera soap provides intense hydration and healing for sensitive, sun-exposed, or irritated skin. It soothes, renews, and leaves skin feeling refreshed and nourished.",
        price: 299,
        mrp: 399,
        discount: "25% OFF",
        image: "images/aloevera_soap_2.jpg",
        thumbnail1: "soap.jpg",
        thumbnail2: "soap.jpg",
        alt: "Aura-Cleanse Aloe Vera Soap - Hydrating Soap for Sensitive Skin",
        size: "100g",
        weight: "100g",
        category: "soothing",
        ingredients: [
            { name: "Fresh Aloe Vera Gel", description: "Deeply hydrating and healing" },
            { name: "Cucumber Extract", description: "Cooling and soothing" },
            { name: "Vitamin E", description: "Protects and nourishes skin" }
        ],
        rating: 4.8,
        reviews: 156
    },
    {
        id: 'product-12',
        name: "Charcoal",
        subtitle: "Deep Pore Cleanser",
        description: "Activated charcoal draws out impurities, toxins, and excess oil from deep within pores for ultra-clean skin.",
        detailedDescription: "Activated Charcoal soap acts like a magnet, drawing out impurities, toxins, and excess oil from deep within pores for thoroughly cleansed, ultra-clean skin.",
        price: 349,
        mrp: 449,
        discount: "22% OFF",
        image: "soap.jpg",
        thumbnail1: "soap.jpg",
        thumbnail2: "soap.jpg",
        alt: "Aura-Cleanse Charcoal Soap - Deep Pore Cleansing Soap with Activated Charcoal",
        size: "100g",
        weight: "100g",
        category: "detox",
        ingredients: [
            { name: "Activated Charcoal", description: "Draws out impurities and toxins" },
            { name: "Bentonite Clay", description: "Deep cleanses pores" },
            { name: "Tea Tree Oil", description: "Antibacterial and purifying" }
        ],
        rating: 4.5,
        reviews: 93
    },
    {
        id: 'product-13',
        name: "Neem",
        subtitle: "Heals Acne",
        description: "Neem's antibacterial properties combat acne while antioxidants fight signs of aging for youthful skin.",
        detailedDescription: "Neem soap uses the powerful antibacterial properties of neem to combat acne and blemishes while antioxidants fight signs of aging, promoting clear, youthful-looking skin.",
        price: 319,
        mrp: 419,
        discount: "24% OFF",
        image: "images/neem_soap_2.jpg",
        thumbnail1: "soap.jpg",
        thumbnail2: "soap.jpg",
        alt: "Aura-Cleanse Neem Soap - Acne Healing Soap with Neem Antibacterial Properties",
        size: "100g",
        weight: "100g",
        category: "medicinal",
        ingredients: [
            { name: "Neem Leaves", description: "Powerful antibacterial and antifungal" },
            { name: "Tulsi", description: "Purifies and protects skin" },
            { name: "Turmeric", description: "Reduces inflammation and brightens" }
        ],
        rating: 4.7,
        reviews: 134
    }
];
